version: "3.7"

services:
  app:
    image: keelezibel/fastapi:1.0.0
    volumes:
      - ./src:/app
    ports:
      - "8050:8000"
    command: python3 -m uvicorn infer:app --host 0.0.0.0
    # tty: true